samples = [
    ["I really enjoyed the movie", "positive"],
    ["The book was not interesting", "negative"],
    ["The food at the restaurant was amazing", "positive"],
    ["I had a terrible experience with the customer service", "negative"],
    ["The concert was fantastic", "positive"],
    ["I found the product to be of poor quality", "negative"],
    ["The hotel exceeded my expectations", "positive"],
    ["The traffic was unbearable", "negative"],
    ["The play was captivating", "positive"],
    ["I was disappointed with the outcome", "negative"],
    ["The car had excellent performance", "positive"],
    ["The hotel room was dirty and uncomfortable", "negative"],
    ["The movie had a confusing plot", "negative"],
    ["The staff at the restaurant was friendly and attentive", "positive"],
    ["The book kept me hooked till the end", "positive"],
    ["The car broke down within a week of purchase", "negative"],
    ["The hotel had a beautiful view of the ocean", "positive"],
    ["The service at the store was slow and inefficient", "negative"],
    ["The movie had great special effects", "positive"],
    ["The product was delivered on time and in good condition", "positive"],
    ["The car had a comfortable interior", "positive"],
    ["The hotel room smelled bad and was poorly maintained", "negative"],
    ["The book had a predictable ending", "negative"],
    ["The customer support was unresponsive and unhelpful", "negative"],
    ["The movie made me laugh throughout", "positive"],
    ["The product did not meet my expectations", "negative"],
    ["The car had a smooth ride", "positive"],
    ["The hotel staff was rude and unprofessional", "negative"],
    ["The book had well-developed characters", "positive"],
    ["The service at the restaurant was excellent", "positive"],
    ["The movie was boring and lacked excitement", "negative"],
    ["The product was of high quality", "positive"],
    ["The car had poor fuel efficiency", "negative"],
    ["The hotel had comfortable beds and clean rooms", "positive"],
    ["The staff at the store was helpful and knowledgeable", "positive"],
    ["The movie had a powerful and emotional storyline", "positive"],
    ["The product was overpriced for its quality", "negative"],
    ["The car had a sleek and stylish design", "positive"],
    ["The hotel had a noisy and disruptive environment", "negative"],
    ["The book had beautiful descriptions and vivid imagery", "positive"],
    ["The service at the restaurant was slow and unattentive", "negative"],
    ["The movie had poor acting and weak dialogue", "negative"],
    ["The product exceeded my expectations", "positive"],
    ["The car had frequent mechanical issues", "negative"],
    ["The hotel had a convenient location and easy access to attractions", "positive"],
    ["The staff at the store was unfriendly and unhelpful", "negative"],
    ["The movie had stunning cinematography and visually appealing scenes", "positive"],
    ["The product was difficult to use and had a steep learning curve", "negative"],
    ["The car had advanced safety features", "positive"],
    ["The hotel had a lack of cleanliness and hygiene", "negative"],
    ["The book had an engaging and suspenseful plot", "positive"],
    ["The service at the restaurant was subpar and disappointing", "negative"],
    ["The movie had a confusing and convoluted storyline", "negative"],
    ["The product was user-friendly and intuitive", "positive"],
    ["The car had uncomfortable seats and limited legroom", "negative"],
    ["The hotel had friendly and accommodating staff", "positive"],
    ["The staff at the store was unprofessional and rude", "negative"],
    ["The movie had a thought-provoking and impactful message", "positive"],
    ["The product failed to meet basic functionality requirements", "negative"],
    ["The car had excellent handling and responsive steering", "positive"],
    ["The hotel had poor customer service and unhelpful staff", "negative"],
    ["The book had well-researched information and valuable insights", "positive"],
    ["The service at the restaurant was prompt and efficient", "positive"],
    ["The movie had poor production quality and amateurish acting", "negative"],
    ["The product provided exceptional value for the price", "positive"],
    ["The car had outdated technology and limited features", "negative"],
    ["The hotel had a welcoming and comfortable ambiance", "positive"],
    ["The staff at the store was knowledgeable and friendly", "positive"],
    ["The movie had a gripping and suspenseful plot", "positive"],
    ["The product was poorly designed and prone to malfunctions", "negative"],
    ["The car had impressive acceleration and power", "positive"]
]
